In [80]:
import pandas as pd

In [81]:
df = pd.read_csv("scores.csv")

In [82]:
# Renaming the Unnamed column
df.rename(columns={'Unnamed: 1':'FOW'}, inplace=True)

In [122]:
# Row indexes where he bowling and batting scorecard for different innings begin
bowler_indexes = df.loc[df['BATSMEN'] == 'Bowling'].index.tolist()
batsmen_indexes = df.loc[df['BATSMEN'] == 'BATSMEN'].index.tolist()
# First batting index as -1 because first innings starts at index 0
batsmen_indexes = [-1] + batsmen_indexes

In [142]:
# Break score card into innings
innings = [] # Row indexes of where the inning starts, where the bowling starts and where inning ends
for counter, ini in enumerate(batsmen_indexes):
    # Last inning ends at the end of the data frame so df.shape[0]
    if counter == len(batsmen_indexes) - 1:
        innings.append((batsmen_indexes[counter] + 1, bowler_indexes[counter] + 1, df.shape[0]))
    else:
        innings.append((batsmen_indexes[counter] + 1, bowler_indexes[counter] + 1, batsmen_indexes[counter + 1]))

In [143]:
innings

[(0, 12, 18), (19, 31, 36), (37, 49, 54)]

In [151]:
ini1_bat = df[innings[0][0]:innings[0][1] - 1]
ini1_bowl = df[innings[0][1]:innings[0][2]]

In [153]:
ini1_bat

           BATSMEN                   FOW    R    B    M  4s 6s      SR
0          PP Shaw          c & b Bishoo  134  154  238  19  0   87.01
1         KL Rahul         lbw b Gabriel    0    4    6   0  0    0.00
2        CA Pujara    c †Dowrich b Lewis   86  130  194  14  0   66.15
3      V Kohli (c)      c Bishoo b Lewis  139  230  341  10  0   60.43
4        AM Rahane    c †Dowrich b Chase   41   92  127   5  0   44.56
5        RR Pant †       c Paul b Bishoo   92   84  121   8  4  109.52
6        RA Jadeja               not out  100  132  152   5  5   75.75
7         R Ashwin   c †Dowrich b Bishoo    7   15   18   1  0   46.66
8    Kuldeep Yadav          lbw b Bishoo   12   32   33   2  0   37.50
9         UT Yadav  c Lewis b Brathwaite   22   24   22   0  2   91.66
10  Mohammed Shami               not out    2    6   21   0  0   33.33

In [154]:
ini1_bowl

          BATSMEN   FOW  R    B  M    4s 6s SR
12     ST Gabriel    21  1   84  1  4.00  0  2
13       KMA Paul    15  1   61  0  4.06  0  2
14       SH Lewis    20  0   93  2  4.65  0  0
15       D Bishoo    54  3  217  4  4.01  0  0
16       RL Chase    26  1  137  1  5.26  0  0
17  KC Brathwaite  13.5  1   47  1  3.39  0  0

In [155]:
df

,BATSMEN,FOW,R,B,M,4s,6s,SR
0,PP Shaw,c & b Bishoo,134,154,238,19,0,87.01
1,KL Rahul,lbw b Gabriel,0,4,6,0,0,0.00
2,CA Pujara,c †Dowrich b Lewis,86,130,194,14,0,66.15
3,V Kohli (c),c Bishoo b Lewis,139,230,341,10,0,60.43
4,AM Rahane,c †Dowrich b Chase,41,92,127,5,0,44.56
5,RR Pant †,c Paul b Bishoo,92,84,121,8,4,109.52
6,RA Jadeja,not out,100,132,152,5,5,75.75
7,R Ashwin,c †Dowrich b Bishoo,7,15,18,1,0,46.66
8,Kuldeep Yadav,lbw b Bishoo,12,32,33,2,0,37.50
9,UT Yadav,c Lewis b Brathwaite,22,24,22,0,2,91.66
10,Mohammed Shami,not out,2,6,21,0,0,33.33
11,Bowling,O,M,R,W,Econ,WD,NB
12,ST Gabriel,21,1,84,1,4.00,0,2
13,KMA Paul,15,1,61,0,4.06,0,2
14,SH Lewis,20,0,93,2,4.65,0,0
15,D Bishoo,54,3,217,4,4.01,0,0
16,RL Chase,26,1,137,1,5.26,0,0
17,KC Brathwaite,13.5,1,47,1,3.39,0,0
18,BATSMEN,NaN,R,B,M,4s,6s,SR
19,KC Brathwaite (c),b Mohammed Shami,2,10,11,0,0,20.00
20,KOA Powell,lbw b Mohammed Shami,1,6,21,0,0,16.66
21,SD Hope,b Ashwin,10,22,33,2,0,45.45
22,SO Hetmyer,run out (Jadeja),10,28,34,1,0,35.71
23,SW Ambris,c Rahane b Jadeja,12,20,33,2,0,60.00
24,RL Chase,b Ashwin,53,79,123,8,0,67.08
25,SO Dowrich †,b Kuldeep Yadav,10,35,26,1,0,28.57
26,KMA Paul,c Pujara b Yadav,47,49,55,7,2,95.91
27,D Bishoo,not out,17,26,37,3,0,65.38
28,SH Lewis,b Ashwin,0,3,4,0,0,0.00
29,ST Gabriel,st †Pant b Ashwin,1,10,14,0,0,10.00
30,Bowling,O,M,R,W,Econ,WD,NB
31,Mohammed Shami,9,2,22,2,2.44,0,0
32,UT Yadav,11,3,20,1,1.81,0,0
33,R Ashwin,11,2,37,4,3.36,0,0
34,RA Jadeja,7,1,22,1,3.14,0,0
35,Kuldeep Yadav,10,1,62,1,6.20,0,0
36,BATSMEN,NaN,R,B,M,4s,6s,SR
37,KC Brathwaite (c),c Shaw b Ashwin,10,30,31,2,0,33.33
38,KOA Powell,c Shaw b Kuldeep Yadav,83,93,128,8,4,89.24
39,SD Hope,lbw b Kuldeep Yadav,17,34,34,1,1,50.00
40,SO Hetmyer,c Rahul b Kuldeep Yadav,11,11,10,0,1,100.00
41,SW Ambris,st †Pant b Kuldeep Yadav,0,3,3,0,0,0.00
42,RL Chase,c Ashwin b Kuldeep Yadav,20,24,26,3,0,83.33
43,SO Dowrich †,not out,16,64,64,1,0,25.00
44,KMA Paul,c Yadav b Jadeja,15,15,14,2,1,100.00
45,D Bishoo,c †Pant b Ashwin,9,12,11,2,0,75.00
46,SH Lewis,lbw b Jadeja,4,15,11,1,0,26.66
47,ST Gabriel,c Kuldeep Yadav b Jadeja,4,5,6,1,0,80.00
48,Bowling,O,M,R,W,Econ,WD,NB
49,Mohammed Shami,3,0,11,0,3.66,0,1
50,R Ashwin,18,2,71,2,3.94,0,0
51,UT Yadav,3,0,16,0,5.33,0,0
52,Kuldeep Yadav,14,2,57,5,4.07,0,0
53,RA Jadeja,12.5,1,35,3,2.72,0,0